name: Auto-merge Dependabot PRs

on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      # リポジトリをチェックアウト（ローカルアクションを使用するため）
      - uses: actions/checkout@v4
      
      # このリポジトリのアクションを直接使用
      - uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # dependabot/fetch-metadataのメジャーアップデートは手動で確認
          exclude-packages: 'dependabot/fetch-metadata'